[package]
name = "cati"
version = "0.1.0"
edition = "2021"

[dependencies]
tesseract = "0.15"
image = "0.25"
imageproc = "0.25"
tempfile = "3.19.1"
anyhow = "1.0"
regex = "1.11.1"
colored = "3.0"
clap = { version = "4.5", features = ["derive"] }
